version: '3'
services:
    build:
        image: openjdk:8
        volumes:
            - ./:/app
            - $HOME/.gradle/caches:/root/.gradle/caches
            - $HOME/.gradle/wrapper:/root/.gradle/wrapper
        working_dir: /app
        command: ./gradlew build
