projects:
  lucky-block-forge:
    version: 1.19-13.0
    dependencies:
      java:
        minInclusive: 17
        maxInclusive: 17
      minecraft:
        minInclusive: 1.19
        maxInclusive: 1.19
      forge:
        minInclusive: 41.0.0
        maxExclusive: 42
    devDependencies:
      forge-mappings:
        minInclusive: 1.19
        maxInclusive: 1.19
    lockedDependencies:
      minecraft-forge: 1.19-41.0.17

  lucky-block-fabric:
    version: 1.18.2-13.0
    dependencies:
      java:
        minInclusive: 17
        maxInclusive: 17
      minecraft:
        minInclusive: 1.18.2
        maxInclusive: 1.18.2
      fabric-loader:
        minInclusive: 0.13.0
        maxExclusive: 0.14
      # https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/
      fabric-api:
        minInclusive: 0.48.0+1.18.2
        maxInclusive: 0.48.0+1.18.2
    devDependencies:
      # https://maven.fabricmc.net/net/fabricmc/yarn/
      fabric-mappings:
        minInclusive: 1.18.2+build.1
        maxExclusive: 1.18.3

  lucky-block-bedrock:
    version: 1.18.1-11.0
    dependencies:
      minecraft:
        minInclusive: 1.17
        maxInclusive: 1.17

  custom-lucky-block-java:
    version: 1.19-1.0
    dependencies:
      lucky-block:
        minInclusive: 1.0
      minecraft:
        minInclusive: 1.8.0
        maxExclusive: 1.9
