projects:
  lucky-block-forge:
    version: 1.20.1-13.0
    dependencies:
      java:
        minInclusive: 17
        maxInclusive: 17
      minecraft:
        minInclusive: 1.20.1
        maxInclusive: 1.20.1
      forge:
        minInclusive: 47.1.46
        maxExclusive: 48
    devDependencies:
      forge-mappings:
        minInclusive: 1.20.1
        maxInclusive: 1.20.1
    lockedDependencies:
      minecraft-forge: 1.20.1-47.1.46

  lucky-block-fabric:
    version: 1.20.1-13.0
    dependencies:
      java:
        minInclusive: 17
        maxInclusive: 17
      minecraft:
        minInclusive: 1.20.1
        maxInclusive: 1.20.1
      # latest: https://fabricmc.net/develop/
      fabric-loader:
        minInclusive: 0.14.22
        maxExclusive: 1.0
      # https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/
      fabric-api:
        minInclusive: 0.87.0+1.20.1
        maxInclusive: 0.87.0+1.20.1
    devDependencies:
      # https://maven.fabricmc.net/net/fabricmc/yarn/
      fabric-mappings:
        minInclusive: 1.20.1+build.10
        maxExclusive: 1.20.2

  lucky-block-bedrock:
    version: 1.18.1-11.0
    dependencies:
      minecraft:
        minInclusive: 1.17
        maxInclusive: 1.17

  custom-lucky-block-java:
    version: 1.19.3-2.0
    dependencies:
      lucky-block:
        minInclusive: 1.0
      minecraft:
        minInclusive: 1.9.3
        maxExclusive: 1.10
