projects:
  lucky-block-forge:
    version: 1.20.2-13.0
    dependencies:
      java:
        minInclusive: 17
        maxInclusive: 17
      minecraft:
        minInclusive: 1.20.2
        maxInclusive: 1.20.2
      forge:
        minInclusive: 48.0.30
        maxExclusive: 49
    devDependencies:
      forge-mappings:
        minInclusive: 1.20.2
        maxInclusive: 1.20.2
    lockedDependencies:
      minecraft-forge: 1.20.2-48.0.30

  lucky-block-fabric:
    version: 1.20.2-13.0
    dependencies:
      java:
        minInclusive: 17
        maxInclusive: 17
      minecraft:
        minInclusive: 1.20.2
        maxInclusive: 1.20.2
      # latest: https://fabricmc.net/develop/
      fabric-loader:
        minInclusive: 0.14.24
        maxExclusive: 1.0
      fabric-api:
        minInclusive: 0.90.4+1.20.2
        maxInclusive: 0.90.4+1.20.2
    devDependencies:
      fabric-mappings:
        minInclusive: 1.20.2+build.4
        maxExclusive: 1.20.3

  lucky-block-bedrock:
    version: 1.18.1-11.0
    dependencies:
      minecraft:
        minInclusive: 1.17
        maxInclusive: 1.17

  custom-lucky-block-java:
    version: 1.19.3-2.0
    dependencies:
      lucky-block:
        minInclusive: 1.0
      minecraft:
        minInclusive: 1.9.3
        maxExclusive: 1.10
