modLoader="javafml"
loaderVersion="[26,)"

[[mods]]
modId="lucky"
version="${version}"
displayName="Lucky Block"
authors="Alex Socha"
description="Adds a block with random outcomes"

[[dependencies.lucky]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lucky]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"
