modLoader="javafml"
loaderVersion="[32,)"

[[mods]]
modId="lucky"
version="${version}"
displayName="Lucky Block"
authors="Alex Socha"
description="Adds a block with random outcomes"

[[dependencies.lucky]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lucky]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"
