name: build
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Cache gradle
              uses: actions/cache@v2
              with:
                  path: |
                      - /root/.gradle/caches/
                      - /root/.gradle/wrapper/
                  key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}
            - name: Build with Docker
              run: HOME=/root && ./docker-build.sh
            - name: Variables
              id: variables
              uses: actions/github-script@0.9.0
              with:
                script: |
                    const refName = context.ref.split('/').pop();
                    const isRelease = context.eventName === 'push'
                        && context.ref.startsWith("refs/tags/")
                        && (
                            refName.startsWith('luckyblock-')
                            || refName.startsWith('template-addon-')
                        );
                    
                    core.setOutput('refName', refName);
                    core.setOutput('isRelease', isRelease.toString());
            - name: Deploy
              if: ${{ steps.variables.outputs.isRelease == 'true' }}
              uses: appleboy/scp-action@master
              with:
                  host: luckyblockmod.com
                  username: root
                  key: ${{ secrets.LUCKYBLOCKMOD_COM_KEY }}
                  source: dist/${{ steps.variables.outputs.refName }}
                  target: "~/luckyblock-dist"
                  strip_components: 1
