name: build
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build docs
              run: cd docs && ./build.sh

            - name: Build mod
              run: ./build.sh

            - name: Deploy docs
              if: github.ref == 'refs/heads/master'
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: docs/dist

            - name: Set deployment variables
              id: variables
              uses: actions/github-script@0.9.0
              with:
                script: |
                    const refName = context.ref.split("/").pop();
                    const isRelease = context.eventName === "push"
                        && context.ref.startsWith("refs/tags/")
                        && refName.includes("@");
                    
                    const releaseName = refName.split("@")[0];
                    const releaseVersion = refName.split("@")[1];
                    const releaseFolderName = `${releaseName}-${releaseVersion}`
                    
                    core.setOutput("isRelease", isRelease.toString());
                    core.setOutput("releaseFolderName", releaseFolderName);

            - name: Deploy to CurseForge
              if: ${{ steps.variables.outputs.isRelease == 'true' }}
              run: >
                  docker run
                  --env CURSEFORGE_API_TOKEN=${{ secrets.CURSEFORGE_API_TOKEN }}
                  luckyblock
                  ./gradlew :tools:cli --args="upload-to-curseforge ../dist/${releaseName}-${releaseVersion}"
