name: build
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Cache gradle
              uses: actions/cache@v2
              with:
                  path: |
                      - /root/.gradle/caches/
                      - /root/.gradle/wrapper/
                  key: ${{ runner.os }}-${{ hashFiles('build.gradle') }}
            - name: Build with docker-compose
              run: HOME=/root && ./docker-build.sh
